### ISSUE TITLE
[bug] setting storageNodes after installation cause all hwameistor pods deleted 

### ISSUE THREAD

**Issue by alexzhc** [hwameistor/hwameistor#117]
Kubernetes version: 1.24.3

After deploying hwameistor with `storageNodes` left empty, set `storageNodes` by `helm -n hwameistor upgrade hwameistor ./helm/hwameistor --set "storageNodes={k8s-worker-1,k8s-worker-2,k8s-worker-3}"`. 

The command succeeds but then all pods under hwameistor namespace get terminated.

**Comment by alexzhc** [comment]
If the problem cannot be avoided, please consider changing `storageNodes` to `initialStorageNodes`, and find a way to prevent it from being changed after first helm install. 
```
# initialStorageNodes means the nodes will be used for creating local volumes
initialStorageNodes: []
```

**Comment by alexzhc** [comment]
Suggest improving LDC to allow multiple node name in a single yam: 

```
apiVersion: hwameistor.io/v1alpha1
kind: LocalDiskClaimGroup
metadata:
  name: mybach
  nodeNames:
      - k8s-worker-1
      - k8s-worker-2
  description:
    diskType: HDD
```
