### ISSUE TITLE
The application cannot be scheduled normally

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1448]
```
  Warning  FailedScheduling  40s   hwameistor-scheduler  0/3 nodes are available: 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 3 node(s) didn't match pod affinity rules. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
```

```
time="2024-04-22T09:36:00Z" level=debug msg="adding associated LV(capacity: 1073741824) to pool LocalStorage_PoolHDD, current 1 volume(s)" Module=Scheduler/Resources
time="2024-04-22T09:36:00Z" level=debug msg="Adding a candidate" Module=Scheduler/Resources node=k8s-master total=2
time="2024-04-22T09:36:00Z" level=debug msg="Adding a candidate" Module=Scheduler/Resources node=k8s-node2 total=1
time="2024-04-22T09:36:00Z" level=debug msg="Adding a candidate" Module=Scheduler/Resources node=k8s-node1 total=0
time="2024-04-22T09:36:00Z" level=debug msg="matchable node candidates" Module=Scheduler candidates="k8s-master,k8s-node2,k8s-node1" vols=
time="2024-04-22T09:36:00Z" level=debug msg="Filtered in the node" node=k8s-node2 pod=nginx-local-storage-lvm-949bbbcc5-wkn77
I0422 09:36:00.002272       1 scheduler.go:351] "Unable to schedule pod; no fit; waiting" pod="default/nginx-local-storage-lvm-949bbbcc5-wkn77" err="0/3 nodes are available: 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 3 node(s) didn't match pod affinity rules. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling."
time="2024-04-22T09:36:00Z" level=debug msg="Added a Pod" Module=Scheduler/Resources name=nginx-local-storage-lvm-949bbbcc5-wkn77 namespace=default
```

```
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-node1
                - k8s-node2
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hwameistor-local-storage
            topologyKey: "kubernetes.io/hostname"
```

```
hwameistor-local-storage-8rsr9                             2/2     Running            6 (6h29m ago)     3d2h   100.111.156.71   k8s-node1    <none>           <none>            app=hwameistor-local-storage,controller-revision-hash=84bc64d556,pod-template-generation=1
hwameistor-local-storage-csi-controller-6f4f98bccc-9rxtr   6/6     Running            77 (6h28m ago)    3d2h   100.116.59.78    k8s-master   <none>           <none>            app=hwameistor-local-storage-csi-controller,pod-template-hash=6f4f98bccc
hwameistor-local-storage-k5t85                             2/2     Running            6 (6h29m ago)     3d2h   100.64.169.138   k8s-node2    <none>           <none>            app=hwameistor-local-storage,controller-revision-hash=84bc64d556,pod-template-generation=1
hwameistor-local-storage-mb7t6                             2/2     Running            6 (6h29m ago)     3d2h   100.116.59.77    k8s-master   <none>           <none>            app=hwameistor-local-storage,controller-revision-hash=84bc64d556,pod-template-generation=1
```
