### ISSUE TITLE
Filesystem disk pvc can't be created with LDs that have GPT partion table but without partions  

### ISSUE THREAD

**Issue by AmazingPangWei** [hwameistor/hwameistor#1523]
kubectl version:
```
Client Version: v1.28.3+rke2r2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3+rke2r2
```

hwameistor version:
```
v0.14.1
```

I have a disk that have GPT partion table but without partions like this:
```
root@pw-k8s01:~/pangwei/yaml# lsblk /dev/sdh --bytes --pairs --output NAME,SIZE,TYPE,PKNAME,FSTYPE,PTUUID,PTTYPE
NAME="sdh" SIZE="23622320128" TYPE="disk" PKNAME="" FSTYPE="" PTUUID="2a310c44-81c6-4f0c-b6c2-9805299aed5b" PTTYPE="gpt"
```

After I add this disk to my node pw-k8s01, hwameistor scan this disk and generate LD. Note that this disk is considered as **Available** even that there is partition table on this disk:
```
root@pw-k8s01:~/pangwei/yaml# kubectl get ld localdisk-86056bc8f3ff6fb02ac44ffe81019ce4
NAME                                         NODEMATCH   DEVICEPATH   OWNER    PHASE   STATE    AGE
localdisk-86056bc8f3ff6fb02ac44ffe81019ce4   pw-k8s01    /dev/sdh             Available   Active   15h
```

Then I claim this ld and create test pod:
``` yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pw-pvc
spec:
  volumeMode: Filesystem
  storageClassName: hwameistor-storage-disk-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pw-pod
spec:
  containers:
  - name: busybox
    image: busybox:1.31.1
    command:
      - sleep
      - "360000000"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: temp-pvc
      mountPath: /dev/temp-disk
  terminationGracePeriodSeconds: 0
  volumes:
  - name: temp-pvc
    persistentVolumeClaim:
      claimName: pw-pvc
```

Then, you can see this:
```
kubectl describe pod pw-pod:

Events:
  Type     Reason                  Age                 From                     Message
  ----     ------                  ----                ----                     -------
  Normal   Scheduled               25m                 hwameistor-scheduler     Successfully assigned default/pw-pod to pw-k8s01
  Normal   SuccessfulAttachVolume  25m                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-845422de-fd99-4c9b-adca-b0b28ea064f0"
  Warning  FailedMount             53s (x10 over 23m)  kubelet                  MountVolume.SetUp failed for volume "pvc-845422de-fd99-4c9b-adca-b0b28ea064f0" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

Here are local-disk-manager logs: 
```
W0709 02:45:05.561913 3440621 mount_linux.go:382] Configured to mount disk /etc/hwameistor/LocalDisk_PoolHDD/volume/pvc-845422de-fd99-4c9b-adca-b0b28ea064f0 as unknown data, probably partitions but current format is ext4, things might break
I0709 02:45:05.580397 3440621 mount_linux.go:312] `fsck` error fsck from util-linux 2.23.2
fsck.ext2: Bad magic number in super-block while trying to open /dev/sdh
/dev/sdh: 
The superblock could not be read or does not describe a correct ext2
filesystem.  If the device is valid and it really contains an ext2
filesystem (and not swap or ufs or something else), then the superblock
is corrupt, and you might try running e2fsck with an alternate superblock:
    e2fsck -b 8193 <device>

E0709 02:45:05.586127 3440621 mount_linux.go:151] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /etc/hwameistor/LocalDisk_PoolHDD/volume/pvc-845422de-fd99-4c9b-adca-b0b28ea064f0 /var/lib/kubelet/pods/37ceee5f-fcd8-43c1-9097-f0ea83bbf612/volumes/kubernetes.io~csi/pvc-845422de-fd99-4c9b-adca-b0b28ea064f0/mount
Output: mount: wrong fs type, bad option, bad superblock on /dev/sdh,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

{"error":"mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t ext4 -o defaults /etc/hwameistor/LocalDisk_PoolHDD/volume/pvc-845422de-fd99-4c9b-adca-b0b28ea064f0 /var/lib/kubelet/pods/37ceee5f-fcd8-43c1-9097-f0ea83bbf612/volumes/kubernetes.io~csi/pvc-845422de-fd99-4c9b-adca-b0b28ea064f0/mount\nOutput: mount: wrong fs type, bad option, bad superblock on /dev/sdh,\n       missing codepage or helper program, or other error\n\n       In some cases useful info is found in syslog - try\n       dmesg | tail or so.\n","file":"localdiskvolume.go:106","func":"ReconcileMount","level":"error","msg":"Failed to mount /etc/hwameistor/LocalDisk_PoolHDD/volume/pvc-845422de-fd99-4c9b-adca-b0b28ea064f0 to /var/lib/kubelet/pods/37ceee5f-fcd8-43c1-9097-f0ea83bbf612/volumes/kubernetes.io~csi/pvc-845422de-fd99-4c9b-adca-b0b28ea064f0/mount","time":"2024-07-09T02:45:05Z"}
```
