### ISSUE TITLE
[BUG] Unable to modify the scheduler configuration.

### ISSUE THREAD

**Issue by chaunceyjiang** [hwameistor/hwameistor#1714]
I want to add some configurations to the HwameiStor scheduler, as shown below.
However, after making the changes, the configuration automatically reverts to its original state after a few minutes.
I hope that HwameiStor can support configuration modifications to better integrate with other scheduler extensions.

``` yaml 
apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: hwameistor-scheduler
    plugins:
      filter:
        enabled:
          - name: hwameistor-scheduler-plugin
      reserve:
        enabled:
          - name: hwameistor-scheduler-plugin
leaderElection:
  leaderElect: true
  resourceName: hwameistor-scheduler
extenders:
- urlPrefix: "https://nvidia-vgpu-hami-scheduler.nvidia-vgpu.svc:443"
  filterVerb: filter
  bindVerb: bind
  nodeCacheCapable: true
  weight: 1
  httpTimeout: 30s
  enableHTTPS: true
  tlsConfig:
    insecure: true
  managedResources:
  - name: nvidia.com/vgpu
    ignoredByScheduler: true

```
