### ISSUE TITLE
non-HA data volumes migrate failed

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#257]
1.Deploy an nginx application
```
kubectl get pod
NAME                                      READY   STATUS    RESTARTS   AGE
nginx-local-storage-lvm-77c4b4749-qnx72   1/1     Running   0          2m32s
```
2.Modify the replica of nginx to 0
3.create a LocalVolumeMigrate instance
````
apiVersion: hwameistor.io/v1alpha1
kind: LocalVolumeMigrate
metadata:
  namespace: default
  name: localvolumemigrate-1
spec:
  targetNodesNames:
  - k8s-node1
  sourceNodesNames:
  - k8s-node2
  volumeName: pvc-5c1d12ba-7394-4773-9574-16d3c3e4f1e5 
  migrateAllVols: true
````
4
````
kubectl get lvr
NAME                                              CAPACITY     NODE        STATE      SYNCED   DEVICE                                                                  AGE
pvc-5c1d12ba-7394-4773-9574-16d3c3e4f1e5-hxld4l   1073741824   k8s-node1   NotReady   true     /dev/LocalStorage_PoolHDD-HA/pvc-5c1d12ba-7394-4773-9574-16d3c3e4f1e5   110s
pvc-5c1d12ba-7394-4773-9574-16d3c3e4f1e5-ndfcsr   1073741824   k8s-node2   Ready      true     /dev/LocalStorage_PoolHDD-HA/pvc-5c1d12ba-7394-4773-9574-16d3c3e4f1e5   16h
````
