### ISSUE TITLE
Create a convertible data volume, mount the application, convert to 2, expand the PVC, delete the application & data volume. Create a second convertible data volume, mount the application, and fail to migrate

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#295]
Create a convertible data volume, mount the application, convert to 2, expand the PVC, delete the application & data volume. Create a second convertible data volume, mount the application, and fail to migrate。
sc
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-hdd-lvm
provisioner: lvm.hwameistor.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  convertible: "true"
  replicaNumber: "1"
  poolClass: "HDD"
  poolType: "REGULAR"
  volumeKind: "LVM"
  striped: "true"
  csi.storage.k8s.io/fstype: "xfs"
```
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-pvc-lvm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-hdd-lvm
  resources:
    requests:
      storage: 1Gi
```
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-pvc-lvm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-hdd-lvm
  resources:
    requests:
      storage: 1Gi
[root@k8s-master ~]# cat convert.yaml 
apiVersion: hwameistor.io/v1alpha1
kind: LocalVolumeConvert
metadata:
  namespace: default
  name: localvolumeconvert-1
spec:
  volumeName: pvc-20a3f42f-6c18-4c70-8acc-e86842850ed4
  replicaNumber: 2
```
```
apiVersion: hwameistor.io/v1alpha1
kind: LocalVolumeMigrate
metadata:
  namespace: default
  name: localvolumemigrate-1
spec:
  targetNodesNames:
  - k8s-node1
  sourceNodesNames:
  - k8s-node2
  volumeName: pvc-562f5171-819f-4aeb-a69b-01c6975be165
  migrateAllVols: true
```
