### ISSUE TITLE
The docker image is missing ：daocloud.io/daocloud/hwameistor-migrate-rclone:v1.1.2

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#567]
```
  migrate:
    rclone:
      # can use daocloud.io/daocloud/hwameistor-migrate-rclone:v1.1.2 which is exactly same as the following
      imageRepository: rclone/rclone
      tag: 1.53.2
```
