### ISSUE TITLE
Offline package missing rclone image

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#568]
```
  migrate:
    rclone:
      # can use daocloud.io/daocloud/hwameistor-migrate-rclone:v1.1.2 which is exactly same as the following
      imageRepository: rclone/rclone
      tag: 1.53.2
```
