### ISSUE TITLE
LocalVolumeMigrate is different from the document description

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#640]
does not work properly
```
apiVersion: hwameistor.io/v1alpha1
kind: LocalVolumeMigrate
metadata:
  namespace: default
  name: localvolumemigrate-1
spec:
  targetNodesSuggested:
  sourceNode: k8s-node2
  volumeName: pvc-4268ee41-ec31-4d51-ab3e-32f797a831e0
  migrateAllVols: true
```

does not work properly
```
apiVersion: hwameistor.io/v1alpha1
kind: LocalVolumeMigrate
metadata:
  namespace: default
  name: localvolumemigrate-1
spec:
  sourceNode: k8s-node2
  volumeName: pvc-4268ee41-ec31-4d51-ab3e-32f797a831e0
  migrateAllVols: true
```
work normally

```
apiVersion: hwameistor.io/v1alpha1
kind: LocalVolumeMigrate
metadata:
  namespace: default
  name: localvolumemigrate-1
spec:
  targetNodesSuggested: []
  sourceNode: k8s-node2
  volumeName: pvc-4268ee41-ec31-4d51-ab3e-32f797a831e0
  migrateAllVols: true
```
