### ISSUE TITLE
More localdisk attributes are needed

### ISSUE THREAD

**Issue by AmazingPangWei** [hwameistor/hwameistor#984]
Localdisk is a very good crd. What I need to do is getting localdisk from control layer, and I can know all disks info. But currently localDisk exposes few attributes, which is not enough in some certain scenarios.

For example, I need to input block device path when I install rook:

``` yaml
storage:
  nodes:
  - devices:
    - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-ua-datadisk-0
    name: pw1
  - devices:
    - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-ua-datadisk-0
    name: pw3
  - devices:
    - name: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-ua-datadisk-0
    name: pw2
```

I can't get block device path(by-id) from Localdisk, although it's very easy to get for hwameistor.

So, can localdisk expose more attributes(e.g. symbol link(by-id/by-path)、MAJOR、MINOR in udevadm, etc.)?
